
package:
  name: dunovo
  version: '0.7.4'

source:
  git_rev: v0.7.4
  git_url: https://github.com/galaxyproject/dunovo.git

build:
  number: 0
  skip: True  # [py3k or osx]

requirements:
  build:
    - make
    - gcc
    - python

  run:
    - libgcc
    - python
    - mafft 7.221
    - samtools 0.1.18
    - bowtie2 2.2.5
    - networkx
    - paste
    - gawk

test:
  commands:
    - 'correct.py -h > /dev/null'
    - 'align_families.py -h > /dev/null'
    - 'dunovo.py -h > /dev/null'
  imports:
    - networkx

about:
  home: https://github.com/galaxyproject/dunovo
  license: BSD
  license_file: LICENSE.txt
  summary: "Du Novo: A pipeline for processing duplex sequencing data."
