
package:
  name: dunovo
  version: '0.7.4'

source:
  fn: v0.7.4.tar.gz
  url: https://github.com/galaxyproject/dunovo/archive/v0.7.4.tar.gz
  sha256: eb361939b1321c289bb8a4a8db676d24bdee95debcf8100c8ad9425dee90cb8e

build:
  number: 0
  skip: True  # [py3k or osx]

requirements:
  build:
    - make
    - gcc
    - python
    - wget

  run:
    - libgcc
    - python
    - mafft 7.221
    - samtools 0.1.18
    - bowtie2 2.2.5
    - networkx
    - paste
    - gawk

test:
  commands:
    - 'correct.py -h > /dev/null'
    - 'align_families.py -h > /dev/null'
    - 'dunovo.py -h > /dev/null'
  imports:
    - networkx

about:
  home: https://github.com/galaxyproject/dunovo
  license: BSD
  license_file: LICENSE.txt
  summary: "Du Novo: A pipeline for processing duplex sequencing data."
